stages:

  data_ingestion:
    cmd: python data_injection.py
    deps:
      - data_injection.py
    outs:
      - data/raw

  data_preprocessing:
    cmd: python data_preprocessing.py
    deps:
      - data_preprocessing.py
      - data/raw
    outs:
      - data/processed

  feature_engineering:
    cmd: python Feature_Engineering.py
    deps:
      - Feature_Engineering.py
      - data/processed
    outs:
      - data/features

  model_training:
    cmd: python Model_training.py
    deps:
      - Model_training.py
      - data/features
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python Model_evaluation.py
    deps:
      - Model_evaluation.py
      - models/model.pkl
      - data/features
    outs:
      - reports/metrics.json

