stages:

  data_ingestion:
    cmd: python src/data_injection.py
    deps:
      - src/data_injection.py
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed
    outs:
      - data/features

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/features
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/features
    outs:
      - reports/metrics.json

